#!/usr/bin/env bash
set -euo pipefail

# Lines-of-code report for the Papr repo (Rust crates + React frontend).
# Writes loc.md at the repo root.

REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO/loc.md"

count() {
  local total=0 file
  while IFS= read -r -d '' file; do
    total=$((total + $(wc -l < "$file")))
  done
  echo "$total"
}

# Rust: papr-core, papr-cli, papr-server, src-tauri (exclude tests).
rust_src=$(find "$REPO/crates" "$REPO/src-tauri/src" \
  \( -name "*.rs" ! -name "*_test.rs" ! -path "*/tests/*" \) -print0 2>/dev/null | count)
rust_test=$(find "$REPO/crates" "$REPO/src-tauri" \
  \( -name "*_test.rs" -o -name "*_tests.rs" -o -path "*/tests/*.rs" \) -print0 2>/dev/null | count)

# Frontend: Vite + React under src/
frontend_src=$(find "$REPO/src" \( -name "*.tsx" -o -name "*.ts" -o -name "*.css" \) \
  ! -name "*.test.tsx" ! -name "*.test.ts" ! -path "*/__tests__/*" -print0 2>/dev/null | count)
frontend_test=$(find "$REPO/src" \( -name "*.test.tsx" -o -name "*.test.ts" \) -print0 2>/dev/null | count)

total=$((rust_src + rust_test + frontend_src + frontend_test))

{
  echo "# Lines of Code"
  echo ""
  echo "> Generated by \`scripts/loc.sh\` on $(date '+%Y-%m-%d')"
  echo ""
  echo "| Section | Lines |"
  echo "|---------|------:|"
  echo "| Rust — source     | $rust_src      |"
  echo "| Rust — tests      | $rust_test     |"
  echo "| Frontend — source | $frontend_src  |"
  echo "| Frontend — tests  | $frontend_test |"
  echo "| **Total**         | **$total**     |"
} > "$OUT"

echo "Written to $OUT"
